services:
  pytest:
    image: playground_pytest
    build: .
    command: ["uv", "run", "pytest"]
    volumes:
      - "./src:/usr/src/app/src"
      - "./tests:/usr/src/app/tests"
    working_dir: "/usr/src/app"
